# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: run demo

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/**'
      - 'src/**'
      - 'tests/**'
      - 'requirements.txt'
      - 'setup.py'
      - 'pyproject.toml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/**'
      - 'src/**'
      - 'tests/**'
      - 'requirements.txt'
      - 'setup.py'
      - 'pyproject.toml'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Run for your branch'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - main
permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Say Hello
      run: echo "Hello, GitHub Actions!"      
    - name: Show Environment
      run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Make output directory
      run: mkdir -p output/test
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --format=html --htmldir=output/test/flake-report
    - name: Test with pytest
      run: |
        pytest -v -s --junit-xml=output/test/report.xml --self-contained-html --html=output/test/report.html ./tests
    - name: Upload Test Results
      uses: actions/upload-artifact@v7
      with:
        name: test-html-report
        path: output/test
    - name: Display Pytest XML Report
      uses: dorny/test-reporter@v3
      if: ${{ !cancelled() }}       # run this step even if previous step failed
      with:
        name: pytest-xml-report            # Name of the check run which will be created
        path: output/test/*.xml      # Path to test results
        reporter: jest-junit        # Format of test results
  use_artifacts:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
    - name: Download Test Results
      uses: actions/download-artifact@v8
      with:
        name: test-html-report
    - name: Display Test Results
      run: cat report.html
    - name: Display Test XML Report
      run: cat report.xml
    - name: Display Test XML Report with Test Reporter
      uses: dorny/test-reporter@v3
      with:
        artifact: test-results            # artifact name
        name: pytest-xml-report            # Name of the check run which will be created
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: jest-junit              # Format of test results
